
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://openawg.github.io"
https-host: "openawg.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-72887853-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "OpenAWG"
title: "[ OpenAWG ]"
description: "Open source water generation"
# keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"
# 404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

#background-img: "../img/pexels-photo-37487.jpeg"
background-video: "/assets/DehumidifierCloseupWebsite.mp4"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "663 million people - 1 in 10 - lack access to safe water."
  - text: "Twice the population of the United States lives without access to safe water."
  - text: "Every 90 seconds a child dies from a water-related disease."
  - text: "160 million children suffer from stunting and chronic malnutrition linked to water and sanitation."

me-img: "/assets/water_droplets.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "openawg"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/assets/work.png"
    date: "Now"
    description: "Work is currently ongoing for modeling, prototyping, and figuring out budgets and fundraising"
  - image: "/assets/open_source.png"
    date: "February 2016"
    description: "BlueIce Alpha, our first prototype, is open sourced"
  - image: "/assets/burning_man.png"
    date: "February 2016"
    description: "Submitted BRC Honoraria application"
  - image: "/assets/mvp.png"
    date: "January 2016"
    description: "Got an MVP up and running, and connected a reverse osmosis filtration system."
  - image: "/assets/burning_man.png"
    date: "December 2015"
    description: "Invited to submit BRC Honoraria application"
  - image: "/assets/sun_rising.png"
    date: "December 2015"
    description: "With Tedâ€™s climate predictions, we made a rough model and made some engineering decisions on heat pumps"
  - image: "/assets/burning_man.png"
    date: "November 2015"
    description: "Submitted Black Rock City Honoraria letter of intent"
  - image: "/assets/black_rock_desert.png"
    date: "November 2015"
    description: "Met meterologist Ted Hullar and got excellent Black Rock Desert weather data"
  - image: "/assets/proof_of_concept.png"
    date: "September 2015"
    description: "Proof of concept built with spare parts. We started pumping heat around"

# First image of the Timeline

timeline-img: "/assets/water_droplets.png"

###########
# Contact #
###########

#email: "your@email.here"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
#  - title: "twitter"
#    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/openawg/openawg"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

# 404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  FAQ: 'faq'
#   Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "vendor"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
